

###
POST http://localhost:3000/api/teacher/addcourse HTTP/1.1
content-type: application/json

{ 

    "userId":1,
    "courses":[ { "courseId":"1"} ,
               {"titel":"angular"},
           {"description":"good"}
   ]

 }


###

GET  http://localhost:3000/api/users/verify/momonaebuy@gmail.com HTTP/1.1

###
GET  http://localhost:3000/api/users/protected HTTP/1.1