POST http://localhost:3000/api/users/signup HTTP/1.1
content-type: application/json

{ 
     "firstName":"momona", 
    "lastName":"momona", 
     "email":"heru@gmail.com" ,
    "password":"123",
    "phoneNumber": "091648994",
  "email": "momonaebuy@gmail.com",
    "password": "123",
    "role": "STUDENT"

 }

###
POST http://localhost:3000/api/teacher/add HTTP/1.1
content-type: application/json

{ 

    "userId":8,
    "courses":
    [ 
      {"_id":"622f5e3aa1c553e3a9439455","courseTitle":"Acrylic Painting","courseDescription":"Acrylic Painting From Beginner to Master is designed to teach anyone, from beginner to moderate skill levels, all of the fundamentals of acrylics you’ll ever need to create colorful, photo realistic paintings.","courseName":" Microsoft Data Base","catagory":"Art","rating":{"$numberInt":"1"}}
   ]

 }


###

GET  http://localhost:3000/api/users/verify/momonaebuy@gmail.com HTTP/1.1

###
GET  http://localhost:3000/api/users/protected HTTP/1.1